# check the technical writing for various characteristics
- writing/report.md:
  - description: Ensure that report.md file exists in the writing/ directory
    check: ConfirmFileExists
  - description: Write a minimum number of meaningful words (300) in the reflection
    check: CountFileWords
    options:
      count: 600
      exact: false
  - description: Complete all TODOs, remove the TODO markers in the reflection.md
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (6) in repository
  check: CountCommits
  options:
    count: 1
